Repository ZeusLN/zeus, pull requests merged in 2024-11, with the labels that each got.

#2502 Android only: Set 'setRecentsScreenshotEnabled' to false to avoid data leak via recents
  android/app/src/main/java/com/zeus/MainActivity.kt
Labels: Android, Privacy, Security

#2488 [feature] Activity: CSV Export
  locales/en.json
  models/Invoice.ts
  models/Payment.ts
  models/Transaction.ts
  utils/ActivityFilterUtils.test.ts
  views/Activity/Activity.tsx
  views/Activity/ActivityFilter.tsx
  views/Activity/ActivityToCsv.tsx
  views/Invoice.tsx
  views/Payment.tsx
  views/Transaction.tsx
Labels: Activity

#2510 GitHub Workflows: Build Android: show hashes
  .github/workflows/build-android.yml
  build.sh
Labels: Android, GitHub Workflows, Build process

#2511 GitHub Workflows: Build Android: upload artifacts
  .github/workflows/build-android.yml
Labels: Reproducible builds, Android, GitHub Workflows, Build process

#2512 External account workflow fixes
  stores/ChannelsStore.ts
  views/HandleAnythingQRScanner.tsx
Labels: External accounts

#2519 PSBT: BC-UR: use 'crypto-psbt' instead of 'bytes' formatting
  views/HandleAnythingQRScanner.tsx
  views/PSBT.tsx
Labels: QR Codes, External accounts, BCUR

#2521 ZEUS Pay: new device check
  stores/LightningAddressStore.ts
  views/Settings/LightningAddress/index.tsx
Labels: ZEUS Pay

#2524 ZEUS-2523: Bug fix: Coins: external wallets marked hidden appear in tab nav
  components/AccountFilter.tsx
Labels: Bug, External accounts

#2522 Visualize channel reserve capacity
  components/BalanceSlider.tsx
  components/Channels/BalanceBar.tsx
  components/Channels/ChannelItem.tsx
  components/HopPicker.tsx
  components/KeyValue.tsx
  models/Channel.ts
  utils/ThemeUtils.ts
  views/Channels/Channel.tsx
Labels: Channels

#2527 Refactor: remove Sats component
  components/Sats.tsx
  views/Routing/RoutingHeader.tsx
Labels: Refactor

#2528 Receive: do not place 0 into amount input field
  views/Receive.tsx
Labels: UX

#2532 Channels: fixed aliases
  stores/ChannelsStore.ts
Labels: Channels, Enhancement

#2533 LND: coin control backwards compatibility
  stores/TransactionsStore.ts
  utils/handleAnything.ts
Labels: Bug, LND, Coin control

#2535 Channels: reserve updates
  components/Amount.tsx
  components/BalanceSlider.tsx
  components/Channels/ChannelItem.tsx
  components/HopPicker.tsx
  components/LSPS1OrderResponse.tsx
  components/text/Body.tsx
  models/Channel.ts
  stores/ChannelsStore.ts
  utils/ThemeUtils.ts
  views/Channels/Channel.tsx
  views/Channels/ChannelsPane.tsx
Labels: Channels

#2537 deps: pull react-native-qrcode-local-image into zeus_modules
  components/QRCodeScanner.tsx
  ios/Podfile.lock
  package.json
  patches/rnqli-build.gradle.patch
  yarn.lock
  zeus_modules/@remobile/react-native-qrcode-local-image/.gitignore
  zeus_modules/@remobile/react-native-qrcode-local-image/.npmignore
  zeus_modules/@remobile/react-native-qrcode-local-image/LICENSE
  zeus_modules/@remobile/react-native-qrcode-local-image/README.md
  zeus_modules/@remobile/react-native-qrcode-local-image/android/build.gradle
  zeus_modules/@remobile/react-native-qrcode-local-image/android/src/main/AndroidManifest.xml
  zeus_modules/@remobile/react-native-qrcode-local-image/android/src/main/java/com/remobile/qrcodeLocalImage/RCTQRCodeLocalImage.java
  zeus_modules/@remobile/react-native-qrcode-local-image/android/src/main/java/com/remobile/qrcodeLocalImage/RCTQRCodeLocalImagePackage.java
  zeus_modules/@remobile/react-native-qrcode-local-image/index.js
  zeus_modules/@remobile/react-native-qrcode-local-image/ios/RCTQRCodeLocalImage.xcodeproj/project.pbxproj
  zeus_modules/@remobile/react-native-qrcode-local-image/ios/RCTQRCodeLocalImage.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  zeus_modules/@remobile/react-native-qrcode-local-image/ios/RCTQRCodeLocalImage/RCTQRCodeLocalImage.h
  zeus_modules/@remobile/react-native-qrcode-local-image/ios/RCTQRCodeLocalImage/RCTQRCodeLocalImage.m
  zeus_modules/@remobile/react-native-qrcode-local-image/package.json
  zeus_modules/@remobile/react-native-qrcode-local-image/react-native-qrcode-local-image.podspec
Labels: Dependencies

#2536 ZEUS Pay: update relay sig when Nostr key updated
  stores/LightningAddressStore.ts
  views/Settings/LightningAddress/NostrKeys.tsx
Labels: ZEUS Pay

#2540 Improve wallet recovery screen
  views/Settings/SeedRecovery.tsx
Labels: Refactor, Wallet recovery

#2545 deps: Remove unused react-native-snap-carousel
  package.json
  yarn.lock
Labels: Dependencies

#2548 deps: Update babel packages to consistent version 7.22.15
  package.json
  yarn.lock
Labels: Dependencies

#2549 deps: Remove unused babel plugins
  package.json
  yarn.lock
Labels: Dependencies

#2554 Refresh security settings on screen focus
  stores/SettingsStore.ts
  views/Settings/Security.tsx
Labels: Security

#2563 GitHub Workflows: bump Node to v20
  .github/workflows/lint.yml
  .github/workflows/prettier.yml
  .github/workflows/test.yml
  .github/workflows/tsc.yml
Labels: GitHub Workflows

#2558 Intro: Show explainer inside buttons
  components/Button.tsx
  locales/en.json
  views/Intro.tsx
Labels: Onboarding

#2564 deps: Removed unused packages
  ios/Podfile.lock
  ios/zeus.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: Dependencies

#2555 ZEUS Pay: update regenerate pre-image flow
  locales/en.json
  stores/LightningAddressStore.ts
  views/Settings/LightningAddress/index.tsx
Labels: ZEUS Pay

#2556 Accounts: UX improvements
  components/LayerBalances/OnchainSwipeableRow.tsx
  components/LayerBalances/index.tsx
  stores/UTXOsStore.ts
Labels: Bug, External accounts, UX

#2561 Channels: replace toggle header with tab nav
  components/WalletHeader.tsx
  locales/en.json
  views/Channels/ChannelsPane.tsx
Labels: Design, Channels

#2569 Display info when clicking on swipeable rows while sync
  components/LayerBalances/LightningSwipeableRow.tsx
  components/LayerBalances/OnchainSwipeableRow.tsx
  locales/en.json
Labels: UX

#2572 Hide export icon if activity empty
  views/Activity/Activity.tsx
Labels: Activity, UX

#2573 Use "My Lightning Node" as nickname for Quick Start
  locales/en.json
  views/Intro.tsx
  views/IntroSplash.tsx
  views/Settings/WalletConfiguration.tsx
Labels: UX

#2578 Improve channel tabs layout
  views/Channels/ChannelsPane.tsx
Labels: Design, Channels
