Repository ZeusLN/zeus, pull requests merged in 2025-08, with the labels that each got.

#3147 feat: Swaps Rescue Key
  locales/en.json
  models/Swap.ts
  stores/SwapStore.ts
  views/Settings/Seed.tsx
  views/Settings/SeedRecovery.tsx
  views/Swaps/Refund.tsx
  views/Swaps/SwapDetails.tsx
  views/Swaps/SwapsPane.tsx
  views/Swaps/index.tsx
Labels: Backups, Swaps

#3139 Displaying rounded off amounts with (~) and exact amounts
  components/Amount.tsx
  models/Payment.ts
  views/Activity/Activity.tsx
Labels: Fees, UX

#3203 ZEUS-3200: feat: support hybrid Lightning addresses (BIP-353/BOLT-12 + LNURL-pay)
  components/LayerBalances/LightningSwipeableRow.tsx
  components/LayerBalances/PaymentMethodList.tsx
  utils/handleAnything.ts
  views/ChoosePaymentMethod.tsx
Labels: BOLT 12, LNURL, Payments, LNURL-Pay, Lightning address

#2964 Trigger balance update after sending/receiving funds
  stores/Stores.ts
  stores/TransactionsStore.ts
  views/Receive.tsx
  views/SendingLightning.tsx
Labels: UX

#3228 fix: add approximate symbol for fiat currencies and fix RTL placement
  components/Amount.tsx
Labels: Bug

#3241 [donations] enhancement: Donation
  models/NodeInfo.ts
  views/PaymentRequest.tsx
  views/Settings/PaymentsSettings.tsx
Labels: Donations
