Repository ZeusLN/zeus, pull requests merged in 2025-03, with the labels that each got.

#2819 Sending LN: update timeout explanation
  locales/en.json
Labels: UX

#2880 fix: update nodeInfo currentBlockHeight render condition
  views/NodeInfo.tsx
Labels: Bug

#2882 Channel: display 0-conf Confirmed SCID and ensure renewal
  locales/en.json
  models/Channel.ts
  views/Channels/Channel.tsx
  views/Channels/ChannelsPane.tsx
Labels: Channels, LSPS7

#2883 Update LSP doc link
  views/Settings/LSP.tsx
Labels: Documentation

#2834 dev environment: verify script
  package.json
  yarn.lock
Labels: Development

#2885 LSPS7: clear last order when entering extension flow
  stores/LSPStore.ts
  views/LSPS7/index.tsx
Labels: Bug, LSPS7

#2886 handlePayment: handle false positive on in-flight payment
  stores/TransactionsStore.ts
Labels: Bug, Payments, In-transit payments

#2890 ZEUS-2811: ZEUS Pay: fix Olympus chan check
  views/Settings/LightningAddress/index.tsx
Labels: Bug, ZEUS Pay

#2889 fix: Updated AndroidManifest.xml to redirect to the email app correctly
  android/app/src/main/AndroidManifest.xml
Labels: Bug, Android

#2891 Embedded LND: update log functions
  android/app/src/main/java/com/zeus/LndMobileTools.java
  android/app/src/main/java/com/zeus/MainActivity.kt
  ios/LndMobile/LndMobileTools.m
  ios/LndMobile/LndMobileTools.swift
  lndmobile/LndMobile.d.ts
  views/Settings/EmbeddedNode/LNDLogs.tsx
Labels: Embedded LND, Logs

#2899 ZEUS-2810: Update F-Droid metadata
  metadata/en-US/full_description.txt
  metadata/en-US/images/featureGraphic.jpg
  metadata/en-US/images/icon.png
  metadata/en-US/images/phoneScreenshots/1.png
  metadata/en-US/images/phoneScreenshots/2.png
  metadata/en-US/images/phoneScreenshots/3.png
  metadata/en-US/images/phoneScreenshots/4.png
  metadata/en-US/images/phoneScreenshots/5.png
  metadata/en-US/images/phoneScreenshots/6.png
  metadata/en-US/images/phoneScreenshots/7.png
  metadata/en-US/images/phoneScreenshots/8.png
  metadata/en-US/short_description.txt
  metadata/en-US/title.txt
Labels: F-Droid

#2881 ErrorUtils: handle invalid response data from the server
  locales/en.json
  utils/ErrorUtils.test.ts
  utils/ErrorUtils.ts
Labels: Error handling

#2914 [swaps] Embedded LND: v0.18.5-beta-zeus.swaps.1
  fetch-libraries.sh
Labels: Swaps

#2917 Locales: bridgeJavaStrings: only execute on Android
  views/Settings/Language.tsx
  views/Wallet/Wallet.tsx
Labels: Bug, Android, Translations

#2903 UI: Add dynamic background/text colors to AndroidNfcModal
  components/Modals/AndroidNfcModal.tsx
Labels: Design, UX

#2912 Embedded LND: Open Channel: fund max fix
  lndmobile/channel.ts
Labels: Bug

#2904 Wallets: skip connecting procedures if wallet already active
  views/Settings/Wallets.tsx
Labels: Wallet configuration, Startup

#2910 Fix scan QR from photo
  components/QRCodeScanner.tsx
  ios/Podfile
  package.json
  yarn.lock
  zeus_modules/@remobile/react-native-qrcode-local-image/.gitignore
  zeus_modules/@remobile/react-native-qrcode-local-image/.npmignore
  zeus_modules/@remobile/react-native-qrcode-local-image/LICENSE
  zeus_modules/@remobile/react-native-qrcode-local-image/README.md
  zeus_modules/@remobile/react-native-qrcode-local-image/android/build.gradle
  zeus_modules/@remobile/react-native-qrcode-local-image/android/src/main/AndroidManifest.xml
  zeus_modules/@remobile/react-native-qrcode-local-image/android/src/main/java/com/remobile/qrcodeLocalImage/RCTQRCodeLocalImage.java
  zeus_modules/@remobile/react-native-qrcode-local-image/android/src/main/java/com/remobile/qrcodeLocalImage/RCTQRCodeLocalImagePackage.java
  zeus_modules/@remobile/react-native-qrcode-local-image/index.js
  zeus_modules/@remobile/react-native-qrcode-local-image/ios/RCTQRCodeLocalImage.xcodeproj/project.pbxproj
  zeus_modules/@remobile/react-native-qrcode-local-image/ios/RCTQRCodeLocalImage.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  zeus_modules/@remobile/react-native-qrcode-local-image/ios/RCTQRCodeLocalImage/RCTQRCodeLocalImage.h
  zeus_modules/@remobile/react-native-qrcode-local-image/ios/RCTQRCodeLocalImage/RCTQRCodeLocalImage.m
  zeus_modules/@remobile/react-native-qrcode-local-image/package.json
  zeus_modules/@remobile/react-native-qrcode-local-image/react-native-qrcode-local-image.podspec
Labels: Bug, QR Codes

#2936 Locales: Hindi
  stores/SettingsStore.ts
  utils/LocaleUtils.ts
Labels: Translations
