Repository ZeusLN/zeus, pull requests merged in 2025-05, with the labels that each got.

#3021 Channel and peer connection error clearing in UI
  stores/ChannelsStore.ts
  views/OpenChannel.tsx
Labels: Error handling, UX, Channel funding, Peers

#3014 ZEUS-2992: feat: Implement automatic Cashu mint sweeping based on threshold
  locales/en.json
  stores/CashuStore.ts
  stores/SettingsStore.ts
  views/Settings/EcashSettings.tsx
Labels: Cashu

#3022 fix: menu BackendUtils.supportOffers() is async
  components/LayerBalances/LightningSwipeableRow.tsx
  components/LayerBalances/PaymentMethodList.tsx
  stores/NodeInfoStore.ts
  utils/handleAnything.ts
  views/Menu.tsx
  views/Send.tsx
Labels: Refactor

#3029 refactor: Cashu robustness
  stores/CashuStore.ts
  views/Cashu/UnspentTokens.tsx
Labels: Refactor, Cashu

#3032 feat: new Cashu seed format + BIP-39 export
  App.tsx
  ios/Podfile.lock
  ios/zeus.xcodeproj/project.pbxproj
  locales/en.json
  package.json
  stores/CashuStore.ts
  utils/MigrationUtils.test.ts
  utils/MigrationUtils.ts
  views/Cashu/CashuSeed.tsx
  views/Cashu/LightningAddress/LightningAddressSettings.tsx
  views/SendingOnChain.tsx
  views/Tools/CashuTools.tsx
  yarn.lock
Labels: Backups, Cashu

#3028 fix: LND: custom route hints channel ID
  models/Channel.ts
  stores/InvoicesStore.ts
Labels: Bug, LND

#3033 fix: Item pricing in Square POS mode
  views/Order.tsx
Labels: Bug, Point of Sale

#3003 App startup wallet selection
  locales/en.json
  views/Settings/Wallets.tsx
  views/Wallet/Wallet.tsx
Labels: Bug

#3037 design: Improved icons in menu/settings
  assets/images/SVG/Eye On.svg
  assets/images/SVG/Lock.svg
  assets/images/SVG/PeersContact.svg
  views/Menu.tsx
  views/Settings/Settings.tsx
Labels: Design

#3036 fix: LND: precision bug for inbound fee rate
  backends/LND.ts
  backends/LightningNodeConnect.ts
Labels: Bug, LND, Channels, Fees

#3020 feat: toggle hint icon
  views/LnurlPay/LnurlPay.tsx
  views/LnurlPay/Metadata.tsx
  views/LnurlPay/Success.tsx
Labels: LNURL, LNURL-Pay

#3024 [swaps] update status while loading wallet
  stores/SwapStore.ts
  views/Swaps/Refund.tsx
  views/Swaps/SwapDetails.tsx
  views/Swaps/SwapsPane.tsx
  views/Wallet/Wallet.tsx
Labels: Swaps

#3019 refactor: add or edit fields to Contacts section
  assets/images/SVG/Key Security.svg
  locales/en.json
  views/Settings/AddContact.tsx
Labels: Design, Contacts, UX

#3044 fix: Notifications: check Android for Google Mobile Services
  PushNotificationManager.tsx
Labels: Bug, Android, Notifications

#3046 FontUtils
  components/Modals/InfoModal.tsx
  utils/FontUtils.ts
  views/LightningAddress/ZeusPayPlus.tsx
  views/LightningAddress/ZeusPayPlusPerksList.tsx
Labels: Design, Fonts

#3047 ZEUS-1625: fix: improved clipboard button behavior
  components/WalletHeader.tsx
Labels: Bug, Clipboard

#3050 fix: hiding content on Mint view
  views/Cashu/Mint.tsx
Labels: Bug, Design, Ecash, Cashu

#3041 refactor: HopPicker modal layout
  components/HopPicker.tsx
Labels: Refactor

#2947 [feat] Swaps
  App.tsx
  NavigationService.ts
  android/app/src/main/java/com/zeus/lnc-rn/LncModule.kt
  assets/images/SVG/Arrow_down.svg
  assets/images/SVG/Swap.svg
  components/AmountInput.tsx
  fetch-libraries.sh
  ios/LncMobile/LncModule.mm
  lndmobile/LndMobile.d.ts
  lndmobile/LndMobileInjection.ts
  lndmobile/swaps.ts
  locales/en.json
  package.json
  stores/SettingsStore.ts
  stores/Stores.ts
  stores/SwapStore.ts
  utils/LocaleUtils.ts
  views/Menu.tsx
  views/Send.tsx
  views/SendingLightning.tsx
  views/SendingOnChain.tsx
  views/Swaps/Refund.tsx
  views/Swaps/Settings.tsx
  views/Swaps/SwapDetails.tsx
  views/Swaps/SwapsPane.tsx
  views/Swaps/index.tsx
  views/Wallet/Wallet.tsx
  yarn.lock
  zeus_modules/noble_ecc.ts
Labels: Swaps

#2963 feat: export/import feature for wallet configs
  App.tsx
  assets/images/SVG/ExportImport.svg
  locales/en.json
  package.json
  utils/NodeConfigUtils.test.ts
  utils/NodeConfigUtils.ts
  views/Activity/Activity.tsx
  views/Tools/ActivityExport.tsx
  views/Tools/NodeConfigExportImport.tsx
  views/Tools/index.tsx
  yarn.lock
Labels: Wallet configuration

#3075 fix: mint name text overflow in ecash mint picker
  components/EcashMintPicker.tsx
Labels: Bug, Design, Ecash, Cashu

#3076 POS receipt enhancements + fixes
  views/Cashu/ReceiveEcash.tsx
  views/Order.tsx
  views/Receive.tsx
Labels: Bug, Refactor, Point of Sale, Printer
