Repository ZeusLN/zeus, pull requests merged in 2025-01, with the labels that each got.

#2686 ZEUS-2616: Switch wallet via 'Set wallet config as active' leads to buggy state
  views/Settings/WalletConfiguration.tsx
  views/Settings/Wallets.tsx
Labels: Bug, Wallet configuration

#2667 Contacts: Refactor, bugfixes, improved logic/behaviour
  locales/en.json
  stores/ContactStore.ts
  views/Settings/AddContact.tsx
Labels: Refactor, Contacts

#2678 Wallet Configuration: Use showHideToogle for LNDHub and Eclair password inputs
  views/Settings/WalletConfiguration.tsx
Labels: Wallet configuration

#2705 Prevent displaying Wallets.tsx after enabling "Select node on startup"
  views/Wallet/Wallet.tsx
Labels: Navigation

#2702 ZEUS-2701: Wallets: better highlighting of active node
  components/FeeBreakdown.tsx
  locales/en.json
  views/Channels/Channel.tsx
  views/POS/ProductDetails.tsx
  views/PayCode.tsx
  views/PayCodes.tsx
  views/Settings/Wallets.tsx
Labels: Design, Wallet configuration

#2723 Unify memo handling for sent and received payments (invoice and payment)
  models/Invoice.ts
  models/Payment.ts
  views/Activity/Activity.tsx
  views/Invoice.tsx
  views/Payment.tsx
Labels: Keysend, Activity

#2690 ZEUS-2341: Embedded LND: Seed: allow export of ypriv/zpriv
  App.tsx
  locales/en.json
  package.json
  views/Settings/Seed.tsx
  views/Settings/SeedQRExport.tsx
  yarn.lock
Labels: Embedded LND

#2707 Fix security issues and security-related navigation issues
  utils/NavigationUtils.ts
  views/Lockscreen.tsx
Labels: Security

#2756 Pin Pad: new delete key
  assets/images/SVG/DeleteKey.svg
  components/PinPad.tsx
Labels: Design

#2750 ZEUS-2748: ZEUS Pay: don't allow users to create accounts w/o LSP chan
  backends/CLNRest.ts
  backends/CLightningREST.ts
  backends/Eclair.ts
  backends/EmbeddedLND.ts
  backends/LND.ts
  backends/LightningNodeConnect.ts
  backends/LndHub.ts
  backends/Spark.ts
  locales/en.json
  stores/InvoicesStore.ts
  stores/NodeInfoStore.ts
  utils/BackendUtils.ts
  views/Receive.tsx
  views/Settings/LSP.tsx
  views/Settings/LSPS1/index.tsx
  views/Settings/LightningAddress/index.tsx
  views/Settings/Settings.tsx
  views/Wallet/KeypadPane.tsx
  views/Wallet/Wallet.tsx
Labels: ZEUS Pay

#2765 ZEUS-2762: bolt12: Zeus sends sats when user specifies fiat
  views/Send.tsx
Labels: Bug, Core Lightning, BOLT 12

#2766 ZEUS-2763: CLN payments incorrectly listed as 0-amt
  models/Payment.ts
Labels: Bug, Core Lightning, Payments, CLNRest, Activity

#2767 Remove scan view from navigation stack after usage
  views/NodeQRScanner.tsx
Labels: Camera, Navigation

#2687 ZEUS-2683: Storage: migrate from `react-native-encrypted-storage` to `react-native-keychain`
  backends/LNC/credentialStore.ts
  ios/Podfile.lock
  package.json
  storage/index.ts
  stores/ActivityStore.ts
  stores/ChannelBackupStore.ts
  stores/ContactStore.ts
  stores/InventoryStore.ts
  stores/LSPStore.ts
  stores/LightningAddressStore.ts
  stores/LnurlPayStore.ts
  stores/NotesStore.ts
  stores/PosStore.ts
  stores/SettingsStore.ts
  stores/UTXOsStore.ts
  stores/UnitsStore.ts
  utils/MigrationUtils.test.ts
  utils/MigrationUtils.ts
  utils/handleAnything.test.ts
  views/AddNotes.tsx
  views/ContactDetails.tsx
  views/NostrContacts.tsx
  views/SendingLightning.tsx
  views/SendingOnChain.tsx
  views/Settings/Contacts.tsx
  views/Settings/CurrencyConverter.tsx
  views/Settings/EmbeddedNode/DisasterRecovery.tsx
  views/Settings/LSPS1/Order.tsx
  views/Settings/LSPS1/OrdersPane.tsx
  views/Settings/LSPS1/index.tsx
  views/Settings/Seed.tsx
  views/Settings/WalletConfiguration.tsx
  views/Wallet/BalancePane.tsx
  views/Wallet/Wallet.tsx
  yarn.lock
Labels: Dependencies, Storage

#2768 Add LoadingIndicator to LnurlPay
  views/LnurlPay/LnurlPay.tsx
Labels: LNURL, LNURL-Pay, UX

#2770 Embedded LND: Seed: ypriv/zpriv: cache locally
  views/Settings/SeedQRExport.tsx
Labels: Embedded LND

#2751 Activity: LND: limit to 500 invoices + payments
  backends/CLNRest.ts
  backends/LND.ts
  backends/LightningNodeConnect.ts
  views/Receive.tsx
Labels: LND, Activity
